name: record_windows
description: Windows specific implementation for record package called by record_platform_interface.
version: 1.0.2
homepage: https://github.com/llfbandit/record/tree/master/record_windows

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface: ^1.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/Blue Modern Artificial Intelligence Technology Logo_5.png"
    icon_size: 256 # min:48, max:256, default: 48

flutter:
  plugin:
    implements: record
    platforms:
      windows:
        pluginClass: RecordWindowsPluginCApi

  assets:
    - assets/images/
    - assets/images/Blue Modern Artificial Intelligence Technology Logo_5.png